<?
$PERM["seller"]["9"]="W";
$PERM["seller"]["8"]="R";
$PERM["seller"]["*"]="D";
$PERM["customer"]["9"]="W";
$PERM["customer"]["7"]="R";
$PERM["customer"]["*"]="D";
$PERM["/"]["*"]="R";
$PERM["/"]["G9"]="W";
$PERM["announcements"]["G9"]="W";
$PERM["contacts"]["9"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["9"]="W";
$PERM["company"]["5"]="W";
$PERM[".git"]["9"]="W";
$PERM["login"]["9"]="W";
$PERM["include"]["9"]="W";
$PERM["images"]["9"]="W";
$PERM["about"]["9"]="W";
$PERM["index.php"]["9"]="X";
$PERM["index.php"]["5"]="W";
$PERM["bitrix"]["9"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
?>