<?
$PERM["/"]["*"]="R";
$PERM["/"]["G9"]="X";
$PERM["announcements"]["G9"]="X";
$PERM["index.php"]["9"]="X";
$PERM["index.php"]["5"]="W";
$PERM["bitrix"]["9"]="D";
$PERM["seller"]["8"]="X";
$PERM["seller"]["*"]="D";
$PERM["customer"]["7"]="X";
$PERM["customer"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
?>